# site settings
title: "総合コンテンツ制作サークル"
title_eng: "Comprehensive Contents Creators"
subtitle: "創造と表現"
email: "sokon.meiji@gmail.com"
description: "サークルで運用しているサービス一覧"
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address:
city:
state:
zip_code:
country:
phone:

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 20

# social settings
github_url: "https://github.com/ccc-sokon"
twitter_url: "https://twitter.com/ccc_sokon"
blog_url: "http://sokon.hateblo.jp"
lineat_url: "https://line.me/R/ti/p/%40luq8751d"
atnd_url: "https://atnd.org/groups/sokon"
500px_url:
facebook_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:

# build settings
markdown: kramdown

sass:
  style: compressed